### ISSUE TITLE
I had to change labs to fabs in the MoonRise.cpp file

### ISSUE THREAD

**Issue by Cervidae71** [signetica/MoonRise#3]
Using Arduino IDE, i kept receiving the message labs not declared in this scope. It turns out labs is a non excisting function. I changed it to fabs and now it seems to work.

**Comment by signetica** [comment]
Thanks for the report, I had changed it to labs() in response to a problem Microsoft Visual Studio had with the code.  Now I remember why I used fabs() to begin with.

I've reverted the code back to the use of fabs().

Please let me know if  there are any remaining problems.

**Comment by Cervidae71** [comment]
Great support and thank you for your fast response :)
