### ISSUE TITLE
Missing moon rise time. 

### ISSUE THREAD

**Issue by marius-sucan** [signetica/MoonRise#4]
Hello! 

I think I discovered a bug... 

Based on the testing of this class I discovered that it's not returning the moon rise when it occurs between 23:30 and 00:30 or something. 

Lat/long coords: 46.183, 21.317

query-time1 = 2022 10 17 11 30

Result:
moon-rise1 = 2022 10 16 23 28

query-time2 = 2022 10 17 12 00 

Result:
moon-rise2 = 2022 10 18 00 18

Please notice that the difference between the two queries is just 30 minutes. The moon rise is at 23:28 on 16th and for the next query, it returns the moon rise for the 18th, not the 17th. The 17th is skipped for some reason.  The moon rise for that day should be between the two returned values. 

The issue occurs every month. In November, it's between 15th and 17th... 16th is skipped. The moon rise is again between 23:30 and 00:30. 

I tried feeding it different values to get the moon rise for those specific days, the ones skipped, but without succes. 

Please let me know what the problem is. 

Thank you. 

* the query times may differ on your system, due to GMT offsets. I'm +3 here. 

Best regards, Marius.

**Comment by signetica** [comment]
Generally this type of problem arises from not converting properly to or from UTC.  As a result you get events corresponding to times different from your intended times.

Looking at your location, you should see a moonrise at 10:45pm on the 16th, and the next moonrise at 11:45pm on the 17th.

The time in seconds you should be passing to MoonRise for 2022 10 17 11 30 is 1665995400.

**Comment by marius-sucan** [comment]
I created a function to use as a test case on your end.

``
int testMoonRises() {
  double timeOffset = 3600; // one hour in seconds
  time_t t = 1665781200; // unix timestamp; start point Oct 14 2022 21:00:00 GMT+0000 
  double latitude = 46.183;
  double longitude = 21.317;

  MoonRise mr;
  for (int i = 0; i < 120; ++i)
  {
      mr.calculate(latitude, longitude, t + timeOffset*i);
      printf("Moon rise/set nearest %.24s for latitude %.2f longitude %.2f:\n", ctime(&mr.queryTime), latitude, longitude);
      printf("\tMoon rise at %.24s, Azimuth %.2f\n", ctime(&mr.riseTime), mr.riseAz);
  }

  return 1;
}
``

You can see in the output window, it skips a day.

In my DLL I use gmtime(mr.riseTime) to convert the time into a time struct, and it is all the same.


Please run that code and let me know if it does not skip a day.

Here it skips from `Mon Oct 17 23:45:21 2022` to `Wed Oct 19 00:49:25 2022`. If this is correct, please explain why. I am fully aware I might be wrong, entirely ^_^ . I apologize if this is the case.

Best regards, Marius.

**Comment by signetica** [comment]
Make sure you convert UTC back to your local timezone before printing it.

**Comment by signetica** [comment]
It's possible that Microsoft has ctime() do the time zone adjustment, but maybe not.  I don't use Windows, so I'm not sure.  Let's hope they do.  It should be obvious when you run your program.

The other possibility is that it's just one of those days that doesn't have a moonrise.  Since the moon period is greater than 24 hours, these occur about once a month.

When I get to a computer I'll look at your code.

**Comment by marius-sucan** [comment]
Hello, again. 

For some reason, ctime() seems to be returning local time adjusted times.

I decided to consult a website on this matter (moon rise /set times). Found this table...

https://www.timeanddate.com/moon/@686253

And... it seems there is no moon rise on the 18th. I should have consulted it in the first place. Gosh...

I really feel bad now. I apologize for this false flag bug. 

You may close this issue and mark it as "silly" ^_^. 

Best regards, Marius.
